import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
const styles = StyleSheet.create({
    page: {
        padding: 30,
        fontSize: 10,
        fontFamily: 'Helvetica',
    },
    header: {
        textAlign: 'center',
        marginBottom: 20,
    },
    title: {
        fontSize: 14,
        fontWeight: 'bold',
        marginBottom: 8,
        textDecoration: 'underline',
    },
    section: {
        marginBottom: 10,
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    label: {
        fontWeight: 'bold',
    },
    table: {
        width: 'auto',
        marginTop: 10,
        borderStyle: 'solid',
        borderWidth: 1,
        borderColor: '#000',
    },
    tableRow: {
        flexDirection: 'row',
    },
    tableColHeader: {
        width: '20%',
        backgroundColor: '#eee',
        borderRightWidth: 1,
        borderColor: '#000',
        padding: 4,
        fontWeight: 'bold',
    },
    tableCol: {
        width: '20%',
        borderRightWidth: 1,
        borderColor: '#000',
        padding: 4,
    },
    lastCol: {
        borderRightWidth: 0,
    },
});
const CertificadoPDF = ({ data }) => (React.createElement(Document, null,
    React.createElement(Page, { size: "A4", style: styles.page },
        React.createElement(View, { style: styles.header },
            React.createElement(Text, { style: styles.title }, "CERTIFICADO DE CALIBRACI\u00D3N"),
            React.createElement(Text, null,
                "N\u00B0 ",
                data.certificadoNo)),
        React.createElement(View, { style: styles.section },
            React.createElement(Text, null,
                React.createElement(Text, { style: styles.label }, "Cliente:"),
                " ",
                data.cliente),
            React.createElement(Text, null,
                React.createElement(Text, { style: styles.label }, "Fecha:"),
                " ",
                data.fecha)),
        React.createElement(View, { style: styles.section },
            React.createElement(Text, null,
                React.createElement(Text, { style: styles.label }, "Instrumento:"),
                " ",
                data.instrumento),
            React.createElement(Text, null,
                React.createElement(Text, { style: styles.label }, "Fabricante:"),
                " ",
                data.fabricante)),
        React.createElement(View, { style: styles.section },
            React.createElement(Text, null,
                React.createElement(Text, { style: styles.label }, "Modelo/ID:"),
                " ",
                data.modelo),
            React.createElement(Text, null,
                React.createElement(Text, { style: styles.label }, "N\u00B0 Serie:"),
                " ",
                data.serie)),
        React.createElement(View, { style: styles.section },
            React.createElement(Text, null,
                React.createElement(Text, { style: styles.label }, "Rango:"),
                " ",
                data.rangoMin,
                " - ",
                data.rangoMax),
            React.createElement(Text, null,
                React.createElement(Text, { style: styles.label }, "Tolerancia:"),
                " \u00B1",
                data.tolerancia)),
        React.createElement(View, { style: styles.table },
            React.createElement(View, { style: styles.tableRow },
                React.createElement(Text, { style: [styles.tableColHeader] }, "Referencia"),
                React.createElement(Text, { style: [styles.tableColHeader] }, "Dispositivo"),
                React.createElement(Text, { style: [styles.tableColHeader] }, "Diferencia"),
                React.createElement(Text, { style: [styles.tableColHeader] }, "Tolerancia"),
                React.createElement(Text, { style: [styles.tableColHeader, styles.lastCol] }, "Condici\u00F3n")),
            data.resultados.map((r, i) => (React.createElement(View, { key: i, style: styles.tableRow },
                React.createElement(Text, { style: styles.tableCol }, r.referencia),
                React.createElement(Text, { style: styles.tableCol }, r.dispositivo),
                React.createElement(Text, { style: styles.tableCol }, r.diferencia.toFixed(2)),
                React.createElement(Text, { style: styles.tableCol }, data.tolerancia),
                React.createElement(Text, { style: [styles.tableCol, styles.lastCol] }, r.condicion))))))));
export default CertificadoPDF;
